name: matrix_link_text
description: Easy to use text widget for Flutter apps, which converts inlined urls into working, clickable links. Allows for custom styling. Supports matrix identifiers
version: 0.4.2
author: Aleksander Wo≈∫niak <aleksanderwozniak96@gmail.com>, Sorunome <mail@sorunome.de>
homepage: https://github.com/Sorunome/matrix_link_text

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  http: ^0.13.1
  punycode: ^1.0.0

flutter:
